namespace QiWa.Mysql;

using MySqlConnector;

/// <summary>
/// Abstracts the execution of a database command.
/// Generic over <typeparamref name="TReader"/> so the concrete reader type flows through without casting.
/// Implemented by the real MySqlCommand wrapper and by fakes for unit testing.
/// </summary>
public interface IRawCommand<TReader> : IDisposable
    where TReader : IRawReader
{
    /// <summary>Gets or sets the SQL text to execute.</summary>
    string CommandText { get; set; }

    /// <summary>The auto-increment ID generated by the last INSERT statement.</summary>
    long LastInsertedId { get; }

    /// <summary>Declares a named parameter and its MySQL type (called during prepare).</summary>
    void AddParameter(string name, MySqlDbType type);

    /// <summary>Sets the runtime value of an already-declared parameter.</summary>
    void SetParameterValue(string name, object? value);

    /// <summary>Sends a PREPARE request to the server for this command.</summary>
    Task PrepareAsync(CancellationToken ct);

    /// <summary>Executes INSERT / UPDATE / DELETE and returns the number of affected rows.</summary>
    Task<int> ExecuteNonQueryAsync(CancellationToken ct);

    /// <summary>Executes a scalar query and returns the first column of the first row.</summary>
    Task<object?> ExecuteScalarAsync(CancellationToken ct);

    /// <summary>Executes a SELECT query and returns a concrete <typeparamref name="TReader"/>.</summary>
    Task<TReader> ExecuteReaderAsync(CancellationToken ct);
}
